# Generated by Django 3.0.8 on 2020-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(default='frontend', max_length=50),
            preserve_default=False,
        ),
    ]
