# Generated by Django 3.0.8 on 2020-08-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_specialty_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default='https://place-hold.it/100x60', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default='https://place-hold.it/100x60', max_length=100),
            preserve_default=False,
        ),
    ]
