# Generated by Django 3.0.8 on 2020-08-16 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0005_auto_20200808_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Не ищу работу'), ('2', 'Рассматриваю предложение'), (
                    '3', 'Ищу работу')], max_length=50)),
                ('salary', models.FloatField()),
                ('grade', models.CharField(choices=[('1', 'Стажер'), ('2', 'Джуниор'), ('3', 'Миддл'), (
                    '4', 'Синьор'), ('5', 'Лид')], max_length=50)),
                ('edication', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('portfolio', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
